export const GET_ALL_TOON_PENDING = 'GET_ALL_TOON_PENDING';
export const GET_ALL_TOON_FULFILLED = 'GET_ALL_TOON_FULFILLED';
export const GET_ALL_TOON_REJECTED = 'GET_ALL_TOON_REJECTED';


export const GET_ALL_FAV_PENDING = 'GET_ALL_FAV_PENDING';
export const GET_ALL_FAV_FULFILLED = 'GET_ALL_FAV_FULFILLED';
export const GET_ALL_FAV_REJECTED = 'GET_ALL_FAV_REJECTED';
